# Generated by Django 4.2.6 on 2023-10-19 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='День')),
                ('months', models.CharField(max_length=10, verbose_name='Месяц')),
                ('biceps', models.PositiveIntegerField(blank=True, verbose_name='Обхват бицепса')),
                ('breast', models.PositiveIntegerField(blank=True, verbose_name='Обхват груди')),
                ('waist', models.PositiveIntegerField(blank=True, verbose_name='Обхват талии')),
                ('buttocks', models.PositiveIntegerField(blank=True, verbose_name='Обхват ягодиц')),
                ('hip', models.PositiveIntegerField(blank=True, verbose_name='Обхват бедра')),
            ],
        ),
    ]
