# Generated by Django 4.2.6 on 2023-10-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodysize',
            name='biceps',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват бицепса'),
        ),
        migrations.AlterField(
            model_name='bodysize',
            name='breast',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват груди'),
        ),
        migrations.AlterField(
            model_name='bodysize',
            name='buttocks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват ягодиц'),
        ),
        migrations.AlterField(
            model_name='bodysize',
            name='hip',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват бедра'),
        ),
        migrations.AlterField(
            model_name='bodysize',
            name='waist',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват талии'),
        ),
    ]
