# Generated by Django 4.2.6 on 2023-10-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainning_app', '0002_alter_bodysize_biceps_alter_bodysize_breast_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodysize',
            old_name='months',
            new_name='month',
        ),
    ]
