# Generated by Django 4.2.5 on 2023-10-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainning_app', '0003_rename_months_bodysize_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodysize',
            name='day',
        ),
        migrations.RemoveField(
            model_name='bodysize',
            name='month',
        ),
        migrations.AddField(
            model_name='bodysize',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
