# Generated by Django 4.2.5 on 2023-10-26 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='День')),
                ('month', models.CharField(max_length=10, verbose_name='Месяц')),
                ('eating', models.CharField(max_length=20, verbose_name='Прием пищи')),
                ('dish_1', models.CharField(max_length=20, verbose_name='Блюдо №1')),
                ('weight_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Граммовка блюда №1')),
                ('dish_2', models.CharField(max_length=20, verbose_name='Блюдо №2')),
                ('weight_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Граммовка блюда №2')),
                ('dish_3', models.CharField(max_length=20, verbose_name='Блюдо №3')),
                ('weight_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Граммовка блюда №3')),
                ('dish_4', models.CharField(max_length=20, verbose_name='Блюдо №4')),
                ('weight_4', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Граммовка блюда №4')),
                ('dish_5', models.CharField(max_length=20, verbose_name='Блюдо №5')),
                ('weight_5', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Граммовка блюда №5')),
                ('dish_6', models.CharField(max_length=20, verbose_name='Блюдо №6')),
                ('weight_6', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Граммовка блюда №6')),
            ],
        ),
    ]
