# Generated by Django 4.2.5 on 2023-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BodySize',
            new_name='Eating',
        ),
    ]
