# Generated by Django 4.2.5 on 2023-10-28 09:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_counter', '0002_rename_bodysize_eating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='День')),
                ('month', models.CharField(max_length=10, verbose_name='Месяц')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.RemoveField(
            model_name='eating',
            name='day',
        ),
        migrations.RemoveField(
            model_name='eating',
            name='month',
        ),
        migrations.AddField(
            model_name='eating',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_counter.eatingdate'),
        ),
    ]
