# Generated by Django 4.2.5 on 2023-10-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_counter', '0003_eatingdate_remove_eating_day_remove_eating_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatingdate',
            name='day',
        ),
        migrations.RemoveField(
            model_name='eatingdate',
            name='month',
        ),
    ]
