# Generated by Django 4.2.5 on 2023-10-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_counter', '0005_alter_eating_dish_3_alter_eating_dish_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eating',
            name='dish_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Блюдо №2'),
        ),
    ]
