# Generated by Django 4.2.5 on 2023-10-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_counter', '0007_alter_eating_dish_2_alter_eating_dish_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eating',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_counter.eatingdate', verbose_name='Подтвердите дату'),
        ),
    ]
