# Generated by Django 4.2.5 on 2023-10-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_counter', '0008_alter_eating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eating',
            name='date',
            field=models.ForeignKey(limit_choices_to=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_counter.eatingdate', verbose_name='Подтвердите дату'),
        ),
    ]
