# Generated by Django 4.2.5 on 2023-10-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_counter', '0010_alter_eating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eating',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_counter.eatingdate'),
        ),
    ]
